Package.swift, Sources/SpeziScheduler/Scheduler.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestApp/TestAppDelegate.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj
- Task and Events in the Scheduler Module are currently not persisted across launches of the application.
- This PR uses the Spezi Storage module to enable a local storage of the schedule, tasks, and events in the Spezi Scheduler module.
- Adds UI and unit tests.
=> Add Local Storage and Persistence Functionality for the Scheduler Module

Sources/SpeziScheduler/Schedule.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/SpeziScheduler.docc/SchedulingATask.md, Sources/SpeziScheduler/Task.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestApp/TestAppDelegate.swift
- The current Scheduler API does not allow the scheduling of a task in a random time interval between two defined times.
- Creates an API that defines a `Repetition` type to define a start and end time of the scheduled task.
=> Randomize Scheduling of Task in Time Interval

Sources/SpeziScheduler/Event.swift, Sources/SpeziScheduler/Schedule.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task.swift, Sources/SpeziScheduler/TaskReference.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift
- Tasks are currently surfaced in the application but do not tigger a local notification that would remind a user to complete a task at the time the task should be scheduled.
- Adds the `notifications` parameter to the `Task` type that configures if a local notification should be emitted.
- Local notifications are only emitted after the user has given permission. The method `requestLocalNotificationAuthorization()` on the `Scheduler` type can be used to get permission to send out notifications, e.g., during the onboarding flow.
=> Add Support for Local Notifications

Sources/SpeziScheduler/Event.swift, Sources/SpeziScheduler/Scheduler.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj
- Addresses and issue where the notifications were not properly scheduled when tasks were added after the initial scheduler was created
- Fixes the issue where the scheduler did not refresh a SwiftUI view when a new task was added.
=> Fix Notification Scheduling and Scheduler Refreshing

Sources/SpeziScheduler/Event.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestApp/TestAppDelegate.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift
- Notifications are not triggered when permissions are given after a task has been scheduled.
=> Improve Notification Scheduling and Task Management

.github/workflows/build-and-test.yml, Package.swift, Sources/SpeziScheduler/Event.swift, Sources/SpeziScheduler/Scheduler.swift, Tests/UITests/TestApp.xctestplan, Tests/UITests/TestAppUITests/TestAppUITests.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj, Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme
- Local notifications are not displayed in the app when the app is in the foreground
- The schedule view is not updated when new notifications appear when a user enters the application and the notification was delivered in the background: #12
- Refreshes the schedule components when the application entered the foreground
- Removes notifications from the Notification Center when the task has been fulfilled
- Improves the display logic to display the banner even if the user is having the application in the foreground
=> Fix Scheduler Refresh and Display Notifications When Application is Active

.swiftlint.yml, Sources/SpeziScheduler/Scheduler.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestApp/TestApp.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj
As an application developer utilizing the `Spezi` framework, there is currently no way to determine if the Local Notification authorizations are already granted. This could result in unnecessary onboarding views to grant notification permissions, even though they are already given.
The `Scheduler` module is extended by the `public var localNotificationAuthorization: Bool` flag. This property indicates whether the authorization to deliver local notifications is already given to the app. Note that the flag is an `async get` computed property, meaning one has to `await` the result.
An example usage could be the following:
```swift
struct HealthKitPermissions: View {
@EnvironmentObject var scheduler: Scheduler<FHIR, SomeContext>
var body: some View {
OnboardingView(
...,
action: {
if await …
```
=> Flag that indicates if Local Notification authorization given

Sources/SpeziScheduler/Scheduler.swift
Currently, we publish an `objectWillChange` event that triggers a rerendering of the associated view not on the main UI thread (so the `@MainActor`). 
Publish the event on the main UI thread via `@MainActor`.
- Small fix to publish `objectWillChange` event on main UI thread
--
- #14
--
--
=> Publish rerender event on the main UI thread

.github/workflows/build-and-test.yml, .swiftlint.yml, Sources/SpeziScheduler/Event.swift, Sources/SpeziScheduler/Schedule.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj, Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme
- Scheduling local notifications sometimes does not work or results in double notifications as noted down in #25.
- Improves the mechanism to save local state to disk to ensure that it is available across application launches.
- Improve logging to us OSLog.
- No changes to the public API/
- Functionality is validated using existing UI and unit tests.
=> Improve Notification Handling & Storage of State Information

Sources/SpeziScheduler/Scheduler.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift
- Scheduling sometimes fails due to some inaccuracies and saved notifications across application installations.
- Decreases the scheduling limit to to 56 notifications at the same time.
- Improves timeouts in tests.
=> Improve Test Stability and Scheduling Limit

Sources/SpeziScheduler/Constants.swift, Sources/SpeziScheduler/Scheduler.swift
- Any changes to the name of the generic context results in the generation of a new local storage while which might hinder backwards compatibility of the Scheduler module in case the name or type changes in a backward compatible manner.
- We encounter a crash on iOS 16.6.1 that seems to relate to thin metadata not being available to the runtime to infer the type name in storing information in the local storage module:
- Fixes the issues by adding a constant storage key for elements stored by the Scheduler module.
=> Add a Constant Storage Key

Sources/SpeziScheduler/Scheduler.swift
- We are currently getting crash reports on iOS 16.6.1 about crashes when using the local storage module for storing information in the scheduler.
- Adds additional locking mechanisms for the local storage access to reduce possible errors due to race conditions.
=> Improve Concurrent Access to the Local Storage

Sources/SpeziScheduler/Model/Event.swift, Sources/SpeziScheduler/Scheduler.swift
- `Scheduler` conforms to `DefaultInitializable`
-  Fix issue where tasks that are overdue at creation are not updated
=> Improve Scheduler Initializer and Fix Issue Where Tasks That Are Overdue at Creation Are Not Updated

Sources/SpeziScheduler/Model/Event.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift
Fixing the following issue: https://github.com/StanfordSpezi/SpeziScheduler/issues/36
- New bug fix allows you to add multiple tasks without crashing
- Each of the tasks can now be completed without errors, with each task's updated completion text and icon showing up.
https://github.com/StanfordSpezi/.github/blob/main/DOCUMENTATIONGUIDE.md
DETAILS:
When I try to add multiple tasks in a single day in the schedule that uses SpeziScheduler, running the app causes it to crash, with the error message "Fatal error: Duplicate keys of type 'Event' were found in a Dictionary.
This usually means either that the type violates Hashable's requirements, or
that members of such a dictionary were mutated after insertion. The template app's PICSScheduler file (our project's version of it) initially has …
=> Bug Fix: SpeziScheduler multiple task app crash

.github/workflows/build-and-test.yml, .swiftlint.yml, Package.swift, Sources/SpeziScheduler/Model/TaskList.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/SchedulerLifecycle.swift, Sources/SpeziScheduler/SchedulerStorage.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/UITests/TestApp/ContentView.swift, Tests/UITests/TestApp/TestApp.swift, Tests/UITests/TestApp/TestAppDelegate.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj, Tests/UITests/UITests.xcodeproj/xcshareddata/xcschemes/TestApp.xcscheme
We found it overly complicated to deal with SpeziScheduler in the development process (e.g., testing changes within the simulator or running unit tests against a scheduler implementation).
This PR changes the SchedulerStorage component to not interact with the local storage if running within a simulator environment. This should allow for more rapid development (e.g., no requirement to delete the app in between startups) and help in unit testing scenarios.
Additionally, this PR fixes the Equatable implementation of the `Scheduler` module.
Lastly, we update to the latest Spezi release and remove usage of the `LifecycleHandler` and avoid directly interfacing with the NotificationDelegate. This ensure that we don't override the Notification Center delegate from someone else and, most …
=> Disable persistent storage of Tasks in simulator

Sources/SpeziScheduler/SpeziScheduler.docc/SpeziScheduler.md, Sources/SpeziScheduler/Task/Outcome.swift, Sources/SpeziScheduler/Task/Task.swift, Sources/SpeziScheduler/UserInfo/Property.swift, Sources/SpeziScheduler/UserInfo/UserInfoKey.swift, Sources/SpeziScheduler/UserInfo/UserInfoStorage.swift, Sources/SpeziScheduler/UserInfo/UserStorageCoding.swift, Sources/SpeziSchedulerMacros/UserStorageEntryMacro.swift, Tests/SpeziSchedulerMacrosTest/UserStorageEntryMacroTests.swift
SpeziScheduler uses the property list encoders and decoders by default for UserStorage properties for an efficient encoded representation. Certain types don't quite work well with the property list encoder. For example FHIRs ModelR4 seem to be heavily tailored towards a JSON representation and fail to decode when using property lists. Therefore, this PR adds the ability to customize the encoder and decoder used with a Property.
* Added `coding` argument to the `Property` macro.
Documentation was supplied.
Additional unit testing verifies the updated macro generation.
By submitting creating this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing …
=> Customize encoders and decoders for UserStorage Properties

.github/workflows/build-and-test.yml, Sources/SpeziScheduler/Notifications/Schedule+Notifications.swift, Sources/SpeziScheduler/Schedule/Schedule.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziSchedulerMacros/SpeziSchedulerDiagnostic.swift
- As noted in https://github.com/StanfordSpezi/SpeziTemplateApplication/pull/98, `Scheduler` lost its conformance to `DefaultInitializable`, causing some previews to break in Spezi applications. It is reasonable to assume that `Scheduler` should conform to `DefaultInitializable` (https://github.com/StanfordSpezi/SpeziTemplateApplication/pull/98#issuecomment-2618173033)
- Let Scheduler Conform to `DefaultInitializable`
=> Let Scheduler Conform to DefaultInitializable

Package.swift, Sources/SpeziScheduler/Notifications/LegacyTaskModel.swift, Sources/SpeziScheduler/Notifications/SchedulerNotifications.swift, Sources/SpeziScheduler/Schedule/Schedule.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziSchedulerUI/EventScheduleList.swift, Sources/SpeziSchedulerUI/TodayList.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift
- for some reason, the `Scheduler.queryOutcomes` function incorrectly returns an empty array.
- i have absolutely no idea what exactly is causing this, but it can be fixed by using Swift's `Sequence.filter` function instead passing a `Predicate` to SwiftData
- this issue can be observed in e.g. the TemplateApplication:
1. modify the app to include a button somewhere that triggers a view update
2. launch the app, open and complete the questionnaire scheduled for today
3. everything looks fine (the scheduled event is marked as completed via a giant green checkmark)
4. tap the button to trigger a view update
5. the TodayList will go back to displaying the event as not-yet-completed
- the issue here is that the next view update will trigger a new call to `queryEvents`, which in turn will call …
=> fix `queryOutcomes` returning no results; make `Schedule` conform to `Hashable`

Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task/AllowedCompletionPolicy.swift, Sources/SpeziScheduler/Task/Task.swift, Tests/UITests/TestApp/ScheduleView.swift, Tests/UITests/TestApp/ShadowedOutcomeTestingView.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift, Tests/UITests/UITests.xcodeproj/project.pbxproj
This PR adds an extra check in `createOrUpdateTask` which, in the case of updating an already-existing task, will perform an early return if the update would leave the task unchanged. The old version also had this type of check, but it was only performed after the shadowed outcome handling, meaning that in a situation where there were shadowed outcomes but the task would not need to be updated, the fact that there were shadowed outcomes would take precedence (simply because the check was performed earlier) and the function would unnecessarily throw an error.
- improve `createOrUpdateTask` to better handle shadowed outcomes
n/a
regression test will be added before the PR is merged
By submitting creating this pull request, you agree to follow our [Code of …
=> improve createOrUpdateTask to better handle shadowed outcomes

Sources/SpeziScheduler/UserInfo/UserStorageCoding.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/SpeziSchedulerTests/Utils/ExampleTaskKey.swift
The `createOrUpdateTask` function operates by looking at the parameter it is passed and comparing them to the properties of the current version of the task with a matching id, to determine whether the task needs to be updated (ie, whether we need to create a new version). These comparisons also include the task's context, which is compared by looking at its internal `[String: Data]` representation, where each entry maps a context property name to its value's encoded representation.
This comparison works fine for trivial context values (eg `@Property var value: Int?` or `@Property var value: String?`), since in these cases all values will have a single encoded representation. However, for non-trivial types, this is no longer the case. For example, if we have `@Property(coding: .json) var …
=> avoid unnecessarily creating new task versions in some cases

Package.swift
This PR:
- updates swift-syntax from `600.0.0-prerelease-2024-08-14` to `601.0.1`
- updates SpeziFoundation and SpeziViews
- explicitly adds a the test target's `__Snapshots__` folder to the package manifest
- updated the swift-syntax dependency to the one for Swift 6.1
n/a
the tests (especially the macro-related ones) still pass.
By creating and submitting this pull request, you agree to follow our [Code of Conduct](https://github.com/StanfordSpezi/.github/blob/main/CODE_OF_CONDUCT.md) and [Contributing Guidelines](https://github.com/StanfordSpezi/.github/blob/main/CONTRIBUTING.md):
=> update swift-syntax; some other Package.swift changes

Package.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziSchedulerUI/TestingSupport/SchedulerSampleData.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift, Tests/SpeziSchedulerUITests/SchedulerSampleDataTests.swift
#66 updated the swift-syntax dependency to requiring at least version 601.0.1, which is incompatible with the latest SwiftLint release, which requires exactly 601.0.0.
This isn't an issue when compiling the SpeziScheduler package on its own, or using it in an app that doesn't use the SwiftLint plug in; but when using the plug in this causes the package resolution to fail.
This PR attempts to fix this.
Additionally, this PR updates the `Scheduler` module's API to allow explicitly specifying how the Scheduler should persist its data.
Previously, the Scheduler would decide this on its own, based on the following schema:
- if the app is running in the iOS Simulator, or in a TEST configuration
- → use in-memory persistence
- if the app is running on macOS, and the Scheduler's static …
=> Scheduler persistence control; relax the swift-syntax requirement from `>=601.0.1` to `>=601.0.0`

Package.swift, Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task/AllowedCompletionPolicy.swift, Sources/SpeziScheduler/Task/Event.swift, Sources/SpeziScheduler/Task/Outcome.swift, Sources/SpeziSchedulerUI/EventScheduleList.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift
This PR fixes a bug introduced in #67, where the Scheduler module would end up storing its database into `~/Documents` when running on macOS outside of a sandbox.
The Scheduler module now checks that the current process is sandboxed, and will abort the program if it isn't.
This mainly was an issue in unit tests of other Spezi modules that themselves depended on the Scheduler (eg: SpeziStudy).
This PR also fixes some unrelated DocC issues.
- the `Scheduler` now requires the current process be sandboxed; this change only affects macOS builds, since iOS/watchOS/etc are already always sandboxed
the macOS sandboxing requirement is added to the docs
there is a test for the new behaviour: we verify that creating an on-disk-persisted Scheduler works fine in sandboxed contexts, and fails in …
=> [macOS] prevent escaping the sandbox

Sources/SpeziScheduler/Notifications/SchedulerNotifications.swift, Tests/UITests/TestAppUITests/TestAppUITests.swift
I'm a student from CS342. In my project, I encountered challenges when using `SpeziScheduler` for notifications. I struggled to figure out how to send notifications and, more importantly, how to stop notifications for specific future events without affecting the entire schedule.
I realized that for many digital health apps, handling notifications dynamically — like disabling future reminders after a user action — is a common scenario. However, the existing `SpeziScheduler` documentation lacked sample code for handling these cases, making it hard to understand how to implement this feature.
This PR adds a clear, step-by-step example to the SchedulerNotifications section, showing how to:
* Enable notifications for scheduled tasks
* Mark future events as complete to cancel notifications only …
=> Add Documentation Example for Notification

Sources/SpeziScheduler/Scheduler.swift, Sources/SpeziScheduler/Task/Outcome.swift, Sources/SpeziScheduler/Task/Task.swift, Tests/SpeziSchedulerTests/SchedulerTests.swift
follow-up to #74; attempts to fix another potential SwiftData crash when deleting a `Task`.
the issue here is that deleting a `Task` sometimes fails with SwiftData complaining about an "appropriate default value" not being configured. it doesn't tell is where exactly the default value is missing, but it's presumably the `Outcome`'s `task` property (which is a non-optional `Task`). ostensibly, this should work fine, given the fact that our model specifies cascarding deletion rules where necessary, but it seems like these sometimes aren't applied?
- fixed a potential crash when deleting `Task`s
the public docs are unchanged, but i've added an explainer to the delete function to outline what's going on, and why it's going on.
we have several new tests, to test the deletion of various …
=> fix task deletion
